import { Category, CategoryType } from '../../category/schemas/category.schema';
import { AmenitiesData } from './amenties';

interface CategorySeed extends Omit<Category, '_id' | 'tags'> {
  _id: string;
  tags: string[];
}

// get tags from AmenitiesData
const [
  wifi,
  bedAndMattress,
  clock,
  softBlanket,
  tissuePaper,
  teaTable,
  cushion,
  workDesk,
  bathroomTv,
  fan,
  powerOutlet,
  mineralWater,
  readingLamp,
  contactStaff,
  a4A5Paper,
  handSanitizer,
  projector,
  pen,
  freeDrinks,
  airConditioner,
  tablesAndChairs,
  printerScanner,
] = AmenitiesData;

//
export const CategorySeedData: CategorySeed[] = [
  {
    _id: '693187dcb1d786ad0201e2c3',
    type: CategoryType.SERVICE,
    name: 'Coffee in Bed',
    description: 'Beverages and snacks',
    isActive: true,
    order: 1,
    tags: [
      wifi._id,
      fan._id,
      tablesAndChairs._id,
      softBlanket._id,
      readingLamp._id,
      a4A5Paper._id,
      mineralWater._id,
      handSanitizer._id,
      ,
      tissuePaper._id,
      powerOutlet._id,
      contactStaff._id,
    ],
  },
  {
    _id: '693187dcb1d786ad0201e2c4',
    type: CategoryType.SERVICE,
    name: 'Meeting Room',
    description: 'Electronics and gadgets',
    isActive: true,
    order: 2,
    tags: [
      a4A5Paper._id,
      projector._id,
      pen._id,
      printerScanner._id,
      wifi._id,
      powerOutlet._id,
      freeDrinks._id,
      cushion._id,
      tablesAndChairs._id,
    ],
  },
  {
    _id: '693187dcb1d786ad0201e2c5',
    type: CategoryType.SERVICE,
    name: 'Level Seat',
    description: 'Apparel and accessories',
    isActive: true,
    order: 3,
    tags: [
      tablesAndChairs._id,
      wifi._id,
      softBlanket._id,
      readingLamp._id,
      powerOutlet._id,
      tissuePaper._id,
    ],
  },
  {
    _id: '693187dcb1d786ad0201e2c6',
    type: CategoryType.SERVICE,
    name: 'Studio Bed',
    description: 'Home and living',
    isActive: true,
    order: 4,
    tags: [airConditioner._id, wifi._id, tablesAndChairs._id, powerOutlet._id],
  },
  {
    _id: '693187dcb1d786ad0201e2c7',
    type: CategoryType.SERVICE,
    name: 'Cafe Space',
    description: 'Sports and outdoor gear',
    isActive: true,
    order: 5,
    tags: [airConditioner._id, wifi._id, tablesAndChairs._id, powerOutlet._id],
  },
  {
    _id: '693187dcb1d786ad0201e2c8',
    type: CategoryType.SERVICE,
    name: 'study Box',
    description: 'Books and stationery',
    isActive: true,
    order: 6,
    tags: [
      tablesAndChairs._id,
      wifi._id,
      softBlanket._id,
      readingLamp._id,
      powerOutlet._id,
      tissuePaper._id,
    ],
  },
  {
    _id: '693187dcb1d786ad0201e2c9',
    type: CategoryType.SERVICE,
    name: 'Semi Private Room',
    description: 'Books and stationery',
    isActive: true,
    order: 7,
    tags: [
      bedAndMattress._id,
      softBlanket._id,
      clock._id,
      tablesAndChairs._id,
      wifi._id,
      teaTable._id,
      bathroomTv._id,
      readingLamp._id,
      powerOutlet._id,
      tissuePaper._id,
    ],
  },
  // Product
  {
    _id: '693187dcb1d786ad0201e2d0',
    type: CategoryType.PRODUCT,
    name: 'Coffee',
    description: 'Traditional Vietnamese coffee',
    isActive: true,
    order: 1,
    tags: [],
  },
  // phindi
  {
    _id: '693187dcb1d786ad0201e2d1',
    type: CategoryType.PRODUCT,
    name: 'Phindi',
    description: 'Traditional Vietnamese coffee filter',
    isActive: true,
    order: 2,
    tags: [],
  },
  //tea
  {
    _id: '693187dcb1d786ad0201e2d2',
    type: CategoryType.PRODUCT,
    name: 'Tea',
    description: 'Assorted herbal teas',
    isActive: true,
    order: 3,
    tags: [],
  },
  {
    _id: '693187dcb1d786ad0201e2d3',
    type: CategoryType.PRODUCT,
    name: 'Freeze',
    description: 'Assorted frozen desserts',
    isActive: true,
    order: 4,
    tags: [],
  },
  {
    _id: '693187dcb1d786ad0201e2d4',
    type: CategoryType.PRODUCT,
    name: 'Bánh',
    description: 'Pastry',
    isActive: true,
    order: 5,
    tags: [],
  },
  {
    _id: '693187dcb1d786ad0201e2d5',
    type: CategoryType.PRODUCT,
    name: 'Bánh mì que',
    description: 'Traditional Vietnamese breadsticks',
    isActive: true,
    order: 6,
    tags: [],
  },
  {
    _id: '693187dcb1d786ad0201e2d6',
    type: CategoryType.PRODUCT,
    name: 'Combo',
    description: 'Assorted snack and beverage combo',
    isActive: true,
    order: 7,
    tags: [],
  },
];
